<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationFormType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Repository\UserRepository;

class AccountController extends AbstractController
{
    /**
     * @Route("/profil", name="account_profile")
     */
    public function profileEdit(Request $request, ObjectManager $manager, UserRepository $user) : Response
    {
        $user = $this->getUser();
        $form = $this->createForm(RegistrationFormType::class, $user);


        var_dump($user->getEmail());die;
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}